apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-deployment
  labels:
    app: yolo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: client
          image: dedanwamalwa/yolo-backend:v1.0.0
          ports:
            - containerPort: 5000