---
- name: clone git repository.

  vars:
    repo_url: https://github.com/dedan-wamalwa/yolo.git
    dest_path: /home/vagrant/apps/yolo
    
  git:
    repo: "{{ repo_url }}"
    dest: "{{ dest_path }}"
    version: master